### ISSUE TITLE
loading a shapefile error

### ISSUE THREAD

**Issue by NadineSahin** [abjer/sds#30]
I am trying to load in a shapefile. And yes I have installed Geopandas and imported geopandas and shapely. But I am getting the error shown under the code. Any idea why?

# set the filepath and load in a shapefile
fp = “Desktop/DEU_adm1.shp”
map_df = gpd.read_file(fp)
# check data type so we can see that this is not a normal dataframe, but a GEOdataframe
map_df.head()

 File "<ipython-input-1-edaa88fdf772>", line 2
    fp = “Desktop/DEU_adm1.shp”
                ^
SyntaxError: invalid character in identifier

**Comment by NadineSahin** [comment]
This is how the error looks like (I made the dot, so the arrow point the right place)

 File "<ipython-input-14-edaa88fdf772>", line 2
    fp = “Desktop/DEU_adm1.shp”
..........................^
SyntaxError: invalid character in identifier

**Comment by NadineSahin** [comment]
I tried correcting it a bit:


fp = "DEU_adm1.shp"
map_df = gpd.read_file(fp)

map_df.head()

and got this instead:

OSError                                   Traceback (most recent call last)
<ipython-input-11-fc18c423eaab> in <module>()
      1 # set the filepath and load in a shapefile
      2 fp = "DEU_adm1.shp"
----> 3 map_df = gpd.read_file(fp)
      4 # check data type so we can see that this is not a normal dataframe, but a GEOdataframe
      5 map_df.head()

~\Anaconda3\lib\site-packages\geopandas\io\file.py in read_file(filename, bbox, **kwargs)
     63         reader = fiona.open
     64 
---> 65     with reader(path_or_bytes, **kwargs) as features:
     66         crs = features.crs
     67         if bbox is not None:

~\Anaconda3\lib\site-packages\fiona\__init__.py in open(path, mode, driver, schema, crs, encoding, layer, vfs, enabled_drivers, crs_wkt)
    160                 raise IOError("no such archive file: %r" % archive)
    161         elif path != '-' and not os.path.exists(path):
--> 162             raise IOError("no such file or directory: %r" % path)
    163         c = Collection(path, mode, driver=driver, encoding=encoding,
    164                        layer=layer, vsi=vsi, archive=archive,

OSError: no such file or directory: 'DEU_adm1.shp'
